### for pwm run script
#wandb login 24706ca326383e9462ee49fd7e91f4dde87aa402
### 100-50
#CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 100-50 --step 0 --lr 0.01 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 100-50 --step 1 --lr 0.001 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 0.07;
#CUDA_VISIBLE_DEVICES=0 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=1 run.py  --data_root /home/AIL-net/dataset --overlap --batch_size 80 --dataset city --name PLOP --task 17-2 --step 1 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --test;

### 50
#CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 50 --step 0 --lr 0.01 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 50 --step 1 --lr 0.001 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 0.07;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 50 --step 2 --lr 0.001 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 0.07;
#CUDA_VISIBLE_DEVICES=0 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=1 run.py  --data_root /home/AIL-net/dataset --overlap --batch_size 80 --dataset city --name PLOP --task 13-6 --step 1 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --test;

### 100-10
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 100-10 --step 0 --lr 0.01 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 0.07;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 100-10 --step 1 --lr 0.001 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 0.07;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 100-10 --step 2 --lr 0.001 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 0.07;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 100-10 --step 3 --lr 0.001 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 0.07;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 100-10 --step 4 --lr 0.001 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 0.07;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset --overlap --batch_size 6 --dataset ade --name PLOP --task 100-10 --step 5 --lr 0.001 --epochs 60 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 0.07;
#CUDA_VISIBLE_DEVICES=0 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=1 run.py  --data_root /home/AIL-net/dataset --overlap --batch_size 80 --dataset city --name PLOP --task 13-6s --step 6 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --test;

