### train
#CUDA_VISIBLE_DEVICES=4,5,6,7 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 0 --lr 0.01 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 1;
CUDA_VISIBLE_DEVICES=4,5,6,7 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 1 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 1;
CUDA_VISIBLE_DEVICES=4,5,6,7 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 2 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 1;
CUDA_VISIBLE_DEVICES=4,5,6,7 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 3 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 1;
CUDA_VISIBLE_DEVICES=4,5,6,7 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 4 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 1;
CUDA_VISIBLE_DEVICES=4,5,6,7 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /data/gyang/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 5 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --temperature_c 1;
### test
#CUDA_VISIBLE_DEVICES=1 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=1 test.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 40 --dataset voc --name PLOP --task 15-5s --step 5 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --ckpt /home/plop_cil/checkpoints/step_plop_voc_ove/15-5s-voc_PLOP_5.pth ;
#CUDA_VISIBLE_DEVICES=1 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=1 test.py  --data_root /home/AIL-net/dataset --overlap --batch_size 24 --dataset city --name PLOP --task 17-2 --step 1 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --ckpt /home/plop_cil/checkpoints/step_plop+cil_city/17-2-city_PLOP_1.pth;
#CUDA_VISIBLE_DEVICES=5 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=1 test.py  --data_root  /data/gyang/AIL-net/dataset/PascalVOC12 --overlap --batch_size 40 --dataset voc --name PLOP --task 15-5s --step 5 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --ckpt /data/gyang/PLOP/checkpoints/step/15-5s-voc_PLOP_4.pth ;

#CUDA_VISIBLE_DEVICES=3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=1 run.py  --data_root /data/gyang/AIL-net/dataset/PascalVOC12 --overlap --batch_size 12 --dataset voc --name PLOP --task 15-5s --step 1 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
