### for pwm run script
wandb login 24706ca326383e9462ee49fd7e91f4dde87aa402

CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 0 --lr 0.01 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 1 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 2 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 3 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 4 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 5 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=1 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 80 --dataset voc --name PLOP --task 15-5s --step 5 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/ --test;
